- hosts: webserver
  become: true
  become_user: root
  tasks:
   - name: setting up jenkins repo
     yum_repository:
       name: jenkins
       description: jenkins-stable
       baseurl: https://pkg.jenkins.io/redhat-stable
       gpgcheck: 0

   - name: downloading jenkins key
     rpm_key:
       key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
       state: present

   - name: updating yum
     yum:
      name: yum
      state: latest

   - name: installing openjdk software
     yum:
       name: "java-11-openjdk"
       state: present

   - name: installing jenkins software #it takes some time while downloading jenkins be Subtle
     yum:
       name: jenkins
       state: present

   - name: start the jenkin
     service:
       name: jenkins
       state: started

